spring:
  application:
        name: app-harvest-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: web-logic-service
            uri: ${WEB_LOGIC_URI:http://localhost:8081}

server:
  port: 8080
